In [1]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

doc1 = "He is a lazy boy. She is also lazy."
doc2 = "Neeraj is a lazy person."

bow_vectorizer = CountVectorizer()

X = bow_vectorizer.fit_transform([doc1,doc2])

bow_df = pd.DataFrame(X.toarray(),columns=bow_vectorizer.get_feature_names_out())
bow_df.head()

also  boy  he  is  lazy  neeraj  person  she
0     1    1   1   2     2       0       0    1
1     0    0   0   1     1       1       1    0

In [ ]:
from __future__ import print_function
 
# Ignore warnings dari gensim
import warnings
warnings.filterwarnings(action='ignore', category=UserWarning, module='gensim')
 
import logging
import os.path
import sys
 
from gensim.corpora import WikiCorpus
 
program = os.path.basename(sys.argv[0])
logger = logging.getLogger(program)
 
logging.basicConfig(format='%(asctime)s: %(levelname)s: %(message)s')
logging.root.setLevel(level=logging.INFO)
logger.info("running %s" % ' '.join(sys.argv))
 
namaFileInput = "idwiki-latest-pages-articles.xml.bz2"
namaFileOutput = "wiki.id.text"
 
space = " "
i = 0
 
# Write file ke variabel namaFileOutput encoder utf-8
output = open(namaFileOutput, 'w', encoding='utf-8')
 
# lower=False: huruf kecil dan besar dibedakan
wiki = WikiCorpus(namaFileInput, lemmatize=None, dictionary={}, lower=False)
for text in wiki.get_texts():
    output.write(' '.join(text) + '\n')
    i = i + 1
    if i % 10000 == 0:
        logger.info("Saved " + str(i) + " articles")
 
output.close()
logger.info("Finished Saved " + str(i) + " articles")

In [ ]:
import multiprocessing
import logging
import os.path
import sys
import multiprocessing
from gensim.models import Word2Vec
from gensim.models.word2vec import LineSentence
 
program = os.path.basename(sys.argv[0])
logger = logging.getLogger(program)
 
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s')
logging.root.setLevel(level=logging.INFO)
logger.info("running %s" % ' '.join(sys.argv))
 
namaFileInput = "wiki.id.text"
namaFileOutput = "w2vec_wiki_id300_0.txt"
 
 
# size 300 = 300 dimensi vektor, window 10 = 10 pengaruh kata disekitarnya, min_count 5 = kata-kata yang muncul < 5 kali akan dikeluarkan dari kosakata dan diabaikan selama pelatihan, sg 0 = cbow / sg 1 = skip gram 
model = Word2Vec(LineSentence(namaFileInput), vector_size=300, window=10, min_count=5, sg=0, workers=multiprocessing.cpu_count())
 
# trim unneeded model memory = use (much) less RAM
model.init_sims(replace=True)
model.wv.save_word2vec_format(namaFileOutput, binary=False)

In [ ]:
import gensim
# import gensim.models.keyedvectors as word2vec
# model = gensim.models.Word2Vec.load(namaFileModel)
# model = word2vec.KeyedVectors.load_word2vec_format(namaFileModel, binary=True)

namaFileModel = "w2vec_wiki_id300_0.txt"

sim = model.wv.most_similar("Jakarta")
print("10 kata terdekat dari Jakarta:{}".format(sim))
sim = model.wv.most_similar("Bandung")
print("10 kata terdekat dari Bandung:{}".format(sim))
 
sim = model.wv.similarity("Yogyakarta", "Surakarta")
print("Kedekatan Yogyakarta-Surakarta: {}".format(sim))
sim = model.wv.similarity("Yogyakarta", "Semarang")
print("Kedekatan Yogyakarta-Semarang: {}".format(sim))
 
sim = model.wv.most_similar_cosmul(positive=['minuman', 'rendang'], negative=['makanan'])
print("makanan-rendang, minuman-?: {}".format(sim))
sim = model.wv.most_similar_cosmul(positive=['mobil', 'honda'], negative=['motor'])
print("motor-honda, mobil-?: {}".format(sim))

In [11]:
import numpy as np
np.random.seed(62)
v_revenge = np.array([0,0,1,0,0,0]) #"revenge"
print(v_revenge)

weight = np.random.random_sample((6,3))
print(weight)


hidden_layer_sg = np.dot(v_revenge,weight)
print(hidden_layer_sg)

weight_prime = np.random.random_sample((3,6))
print(weight_prime)

o_the = np.dot(hidden_layer_sg, weight_prime)
print(o_the)


[0 0 1 0 0 0]
[[0.03375471 0.48910751 0.8460851 ]
 [0.411402   0.63141537 0.29094324]
 [0.54280029 0.22818138 0.24027633]
 [0.95345753 0.64581043 0.01785715]
 [0.99612582 0.73519453 0.72194246]
 [0.41049651 0.20378019 0.96210253]]
[0.54280029 0.22818138 0.24027633]
[[0.22447103 0.04778277 0.88384717 0.88913206 0.9627819  0.61117464]
 [0.98581388 0.4030899  0.15691591 0.58744913 0.38452312 0.29390423]
 [0.01757671 0.46686011 0.91006643 0.10251991 0.42861358 0.13086643]]
[0.35101058 0.23008954 0.73422521 0.6412992  0.71332501 0.43025335]


In [12]:
v_the = np.array([0,0,1,0,0,0]) #"the"
print(v_the)
#array([1, 0, 0, 0, 0, 0])
#weight = menggunakan weight yang sama dengan ilustrasi pada Skip-Gram
hidden_layer_cbow = np.dot(v_the,weight)
print(hidden_layer_cbow)
#array([0.43194502, 0.29122914, 0.61185289])
#weight_prime = menggunakan weight_prime yang sama dengan ilustrasi pada Skip-Gram
o_revenge = np.dot(hidden_layer_cbow, weight_prime)
print(o_revenge)
#array([0.47609761, 0.42011332, 0.96415848, 0.85733473, 0.7183283, 0.91285087])

[0 0 1 0 0 0]
[0.54280029 0.22818138 0.24027633]
[0.35101058 0.23008954 0.73422521 0.6412992  0.71332501 0.43025335]
